FROM python:3.11-slim

RUN apt-get update

ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install pipenv

COPY ./Pipfile ./
COPY ./Pipfile.lock ./
RUN pipenv --python 3.11
RUN pipenv install --system --deploy --ignore-pipfile

COPY ./ ./
