# Generated by Django 4.2.3 on 2023-08-14 00:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Não use espaços em branco', regex='\\s')], verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('category', models.CharField(choices=[('F', 'Forest'), ('W', 'Water'), ('A', 'Air'), ('L', 'Animals')], max_length=1, verbose_name='category')),
                ('image', models.ImageField(upload_to='blog_posts', verbose_name='image')),
                ('date', models.DateField(default=datetime.datetime(2023, 8, 13, 21, 16, 31, 170583), verbose_name='date')),
            ],
        ),
    ]
