# Generated by Django 4.2.3 on 2023-08-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_cep_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denouncement',
            name='image',
            field=models.ImageField(upload_to='denouncements'),
        ),
    ]
