# Generated by Django 4.2.3 on 2023-08-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_denouncement_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Denouncement',
        ),
    ]
