# Generated by Django 4.2.3 on 2023-08-07 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_denouncement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntary',
            options={'verbose_name': 'Voluntário', 'verbose_name_plural': 'Voluntários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(default='Sem CEP', max_length=11, validators=[django.core.validators.RegexValidator(message='Insert a valid CEP', regex='\\d{5}-?\\d{3}'), django.core.validators.RegexValidator(inverse_match=True, message="Don't use Whitespaces", regex='/s')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Insert a valid CPF', regex='^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$'), django.core.validators.RegexValidator(inverse_match=True, message="Don't use Whitespaces", regex='/s')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message="Don't use Whitespaces", regex='/s')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message="Don't use Whitespaces", regex='/s')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message="Don't use Whitespaces", regex='/s')], verbose_name='last name'),
        ),
    ]
