# Generated by Django 4.2.3 on 2023-08-07 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_voluntary_options_alter_user_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(default='Sem CEP', max_length=11, validators=[django.core.validators.RegexValidator(message='Digite um CEP válido', regex='\\d{5}-?\\d{3}'), django.core.validators.RegexValidator(inverse_match=True, message='Não use espaços em branco', regex='\\s')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Digite um CPF válido', regex='^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$'), django.core.validators.RegexValidator(inverse_match=True, message='Não use espaços em branco', regex='\\s')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Não use espaços em branco', regex='\\s')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Não use espaços em branco', regex='\\s')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Não use espaços em branco', regex='\\s')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
