# Generated by Django 4.2.3 on 2023-08-07 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_cep_alter_user_cpf_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Digite um CPF válido', regex='^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$'), django.core.validators.RegexValidator(inverse_match=True, message='Não use espaços em branco', regex='\\s')]),
        ),
    ]
